import type { VehicleCatalogModel, VehicleManufacturer } from '../types';

/** UAE-market reference catalog expansion for Splendor operations. */
const now = '2026-08-30T00:00:00.000Z';
const manufacturer = (id: string, name: string, nameAr: string, countryOfOrigin: string): VehicleManufacturer => ({ id, name, nameAr, countryOfOrigin, source: 'oem_official', createdAt: now, updatedAt: now });
const model = (data: Omit<VehicleCatalogModel, 'source' | 'createdAt' | 'updatedAt'>): VehicleCatalogModel => ({ ...data, source: 'oem_official', createdAt: now, updatedAt: now });

export const UAE_CATALOG_EXPANSION_MANUFACTURERS: VehicleManufacturer[] = [
  manufacturer('hyundai', 'Hyundai', 'هيونداي', 'South Korea'),
  manufacturer('kia', 'Kia', 'كيا', 'South Korea'),
  manufacturer('nissan', 'Nissan', 'نيسان', 'Japan'),
  manufacturer('jetour', 'Jetour', 'جيتور', 'China'),
  manufacturer('honda', 'Honda', 'هوندا', 'Japan')
];

export const UAE_CATALOG_EXPANSION_MODELS: VehicleCatalogModel[] = [
  // Hyundai UAE
  model({ id: 'hyundai-palisade', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Palisade', productionYears: '2020-present', bodyStyle: 'suv', engine: '3.8L V6', horsepower: 291, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-palisade-hybrid', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Palisade Hybrid', productionYears: '2026-present', bodyStyle: 'suv', engine: '2.5L Turbo Hybrid', horsepower: 329, transmission: '6-speed automatic', drivetrain: 'awd', fuelType: 'hybrid', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-santa-fe', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Santa Fe', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.5L Turbo I4', horsepower: 277, transmission: '8-speed dual-clutch', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-santa-fe-hybrid', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Santa Fe Hybrid', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.6L Turbo Hybrid', horsepower: 178, transmission: '6-speed automatic', drivetrain: 'awd', fuelType: 'hybrid', doors: 4, seats: 6, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-tucson', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Tucson', productionYears: '2021-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 156, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-tucson-hybrid', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Tucson Hybrid', productionYears: '2021-present', bodyStyle: 'suv', engine: '1.6L Turbo Hybrid', horsepower: 231, transmission: '6-speed automatic', drivetrain: 'awd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-creta', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Creta', productionYears: '2022-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 115, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-creta-grand', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Creta Grand', productionYears: '2022-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 157, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-kona', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Kona', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 147, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-kona-hybrid', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Kona Hybrid', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.6L Hybrid', horsepower: 139, transmission: '6-speed dual-clutch', drivetrain: 'fwd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-kona-electric', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Kona Electric', productionYears: '2024-present', bodyStyle: 'suv', engine: 'Single Electric Motor', horsepower: 201, transmission: 'Single-speed', drivetrain: 'fwd', fuelType: 'electric', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-azera', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Azera', productionYears: '2023-present', bodyStyle: 'sedan', engine: '3.5L V6', horsepower: 300, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-sonata', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Sonata', productionYears: '2024-present', bodyStyle: 'sedan', engine: '2.5L I4', horsepower: 191, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-elantra', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Elantra', productionYears: '2021-present', bodyStyle: 'sedan', engine: '2.0L I4', horsepower: 147, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-accent', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Accent', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 115, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-grand-i10', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Grand i10', productionYears: '2021-present', bodyStyle: 'hatchback', engine: '1.2L I4', horsepower: 83, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-staria', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Staria', productionYears: '2021-present', bodyStyle: 'mpv', engine: '3.5L V6', horsepower: 272, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 9, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-ioniq-5', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Ioniq 5', productionYears: '2021-present', bodyStyle: 'suv', engine: 'Dual Electric Motor', horsepower: 320, transmission: 'Single-speed', drivetrain: 'awd', fuelType: 'electric', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),

  // Kia UAE
  model({ id: 'kia-picanto', manufacturerId: 'kia', make: 'Kia', model: 'Picanto', productionYears: '2024-present', bodyStyle: 'hatchback', engine: '1.2L I4', horsepower: 83, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-pegas', manufacturerId: 'kia', make: 'Kia', model: 'Pegas', productionYears: '2020-present', bodyStyle: 'sedan', engine: '1.4L I4', horsepower: 94, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k3', manufacturerId: 'kia', make: 'Kia', model: 'K3', productionYears: '2024-present', bodyStyle: 'sedan', engine: '1.6L I4', horsepower: 121, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k4', manufacturerId: 'kia', make: 'Kia', model: 'K4', productionYears: '2025-present', bodyStyle: 'sedan', engine: '2.0L I4', horsepower: 147, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k5', manufacturerId: 'kia', make: 'Kia', model: 'K5', productionYears: '2021-present', bodyStyle: 'sedan', engine: '2.5L Turbo I4', horsepower: 290, transmission: '8-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k8', manufacturerId: 'kia', make: 'Kia', model: 'K8', productionYears: '2025-present', bodyStyle: 'sedan', engine: '3.5L V6', horsepower: 296, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-sonet', manufacturerId: 'kia', make: 'Kia', model: 'Sonet', productionYears: '2021-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 115, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-seltos', manufacturerId: 'kia', make: 'Kia', model: 'Seltos', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 158, transmission: '7-speed dual-clutch', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-sportage-l', manufacturerId: 'kia', make: 'Kia', model: 'Sportage L', productionYears: '2025-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 154, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-sorento', manufacturerId: 'kia', make: 'Kia', model: 'Sorento', productionYears: '2024-present', bodyStyle: 'suv', engine: '3.5L V6', horsepower: 268, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-telluride', manufacturerId: 'kia', make: 'Kia', model: 'Telluride', productionYears: '2020-present', bodyStyle: 'suv', engine: '3.8L V6', horsepower: 291, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-carens', manufacturerId: 'kia', make: 'Kia', model: 'Carens', productionYears: '2022-present', bodyStyle: 'mpv', engine: '1.5L Turbo I4', horsepower: 158, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-carnival', manufacturerId: 'kia', make: 'Kia', model: 'Carnival', productionYears: '2025-present', bodyStyle: 'mpv', engine: '3.5L V6', horsepower: 287, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 8, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-ev3', manufacturerId: 'kia', make: 'Kia', model: 'EV3', productionYears: '2025-present', bodyStyle: 'suv', engine: 'Single Electric Motor', horsepower: 201, transmission: 'Single-speed', drivetrain: 'fwd', fuelType: 'electric', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-ev5', manufacturerId: 'kia', make: 'Kia', model: 'EV5', productionYears: '2025-present', bodyStyle: 'suv', engine: 'Dual Electric Motor', horsepower: 308, transmission: 'Single-speed', drivetrain: 'awd', fuelType: 'electric', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-ev6', manufacturerId: 'kia', make: 'Kia', model: 'EV6', productionYears: '2022-present', bodyStyle: 'suv', engine: 'Dual Electric Motor', horsepower: 320, transmission: 'Single-speed', drivetrain: 'awd', fuelType: 'electric', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-ev9', manufacturerId: 'kia', make: 'Kia', model: 'EV9', productionYears: '2024-present', bodyStyle: 'suv', engine: 'Dual Electric Motor', horsepower: 379, transmission: 'Single-speed', drivetrain: 'awd', fuelType: 'electric', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-tasman', manufacturerId: 'kia', make: 'Kia', model: 'Tasman', productionYears: '2025-present', bodyStyle: 'pickup', engine: '2.5L Turbo I4', horsepower: 277, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),

  // Nissan Dubai
  model({ id: 'nissan-patrol', manufacturerId: 'nissan', make: 'Nissan', model: 'Patrol', productionYears: '2025-present', bodyStyle: 'suv', engine: '3.5L Twin-Turbo V6', horsepower: 425, transmission: '9-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-patrol-nismo', manufacturerId: 'nissan', make: 'Nissan', model: 'Patrol Nismo', productionYears: '2025-present', bodyStyle: 'suv', engine: '3.5L Twin-Turbo V6', horsepower: 495, transmission: '9-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-patrol-pro4x', manufacturerId: 'nissan', make: 'Nissan', model: 'Patrol PRO-4X', productionYears: '2025-present', bodyStyle: 'suv', engine: '3.5L Twin-Turbo V6', horsepower: 425, transmission: '9-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-pathfinder', manufacturerId: 'nissan', make: 'Nissan', model: 'Pathfinder', productionYears: '2022-present', bodyStyle: 'suv', engine: '3.5L V6', horsepower: 271, transmission: '9-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-xterra', manufacturerId: 'nissan', make: 'Nissan', model: 'X-Terra', productionYears: '2021-present', bodyStyle: 'suv', engine: '2.5L I4', horsepower: 165, transmission: '7-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-xtrail', manufacturerId: 'nissan', make: 'Nissan', model: 'X-Trail', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.5L I4', horsepower: 181, transmission: 'CVT', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-kicks', manufacturerId: 'nissan', make: 'Nissan', model: 'Kicks', productionYears: '2025-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 139, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-magnite', manufacturerId: 'nissan', make: 'Nissan', model: 'Magnite', productionYears: '2021-present', bodyStyle: 'suv', engine: '1.0L Turbo I3', horsepower: 99, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-altima', manufacturerId: 'nissan', make: 'Nissan', model: 'Altima', productionYears: '2019-present', bodyStyle: 'sedan', engine: '2.5L I4', horsepower: 188, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-z', manufacturerId: 'nissan', make: 'Nissan', model: 'Z', productionYears: '2023-present', bodyStyle: 'coupe', engine: '3.0L Twin-Turbo V6', horsepower: 400, transmission: '9-speed automatic', drivetrain: 'rwd', fuelType: 'petrol', doors: 2, seats: 2, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-z-nismo', manufacturerId: 'nissan', make: 'Nissan', model: 'Z Nismo', productionYears: '2024-present', bodyStyle: 'coupe', engine: '3.0L Twin-Turbo V6', horsepower: 420, transmission: '9-speed automatic', drivetrain: 'rwd', fuelType: 'petrol', doors: 2, seats: 2, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-urvan', manufacturerId: 'nissan', make: 'Nissan', model: 'Urvan', productionYears: '2020-present', bodyStyle: 'van', engine: '2.5L I4', horsepower: 147, transmission: '5-speed manual', drivetrain: 'rwd', fuelType: 'petrol', doors: 4, seats: 15, roofType: 'fixed', countryOfOrigin: 'Japan' }),

  // Jetour UAE
  model({ id: 'jetour-g700', manufacturerId: 'jetour', make: 'Jetour', model: 'G700', productionYears: '2026-present', bodyStyle: 'suv', engine: '2.0L Turbo Plug-in Hybrid', horsepower: 710, transmission: '3-speed DHT', drivetrain: 'awd', fuelType: 'phev', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-t2', manufacturerId: 'jetour', make: 'Jetour', model: 'T2', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 251, transmission: '7-speed dual-clutch', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-t2-idm', manufacturerId: 'jetour', make: 'Jetour', model: 'T2 i-DM', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo Plug-in Hybrid', horsepower: 375, transmission: '3-speed DHT', drivetrain: 'awd', fuelType: 'phev', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-t1', manufacturerId: 'jetour', make: 'Jetour', model: 'T1', productionYears: '2026-present', bodyStyle: 'suv', engine: '1.5L Turbo', horsepower: 156, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-t1-idm', manufacturerId: 'jetour', make: 'Jetour', model: 'T1 i-DM', productionYears: '2026-present', bodyStyle: 'suv', engine: '1.5L Turbo Plug-in Hybrid', horsepower: 201, transmission: '3-speed DHT', drivetrain: 'fwd', fuelType: 'phev', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-dashing', manufacturerId: 'jetour', make: 'Jetour', model: 'Dashing', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.6L Turbo I4', horsepower: 194, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-x50', manufacturerId: 'jetour', make: 'Jetour', model: 'X50', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 154, transmission: '6-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-x70-fl', manufacturerId: 'jetour', make: 'Jetour', model: 'X70 FL', productionYears: '2025-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 154, transmission: '6-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-x70-plus', manufacturerId: 'jetour', make: 'Jetour', model: 'X70 Plus', productionYears: '2021-present', bodyStyle: 'suv', engine: '1.6L Turbo I4', horsepower: 194, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Honda UAE
  model({ id: 'honda-city', manufacturerId: 'honda', make: 'Honda', model: 'City', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 119, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-civic', manufacturerId: 'honda', make: 'Honda', model: 'Civic', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.5L Turbo I4', horsepower: 180, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-civic-type-r', manufacturerId: 'honda', make: 'Honda', model: 'Civic Type R', productionYears: '2023-present', bodyStyle: 'hatchback', engine: '2.0L Turbo I4', horsepower: 315, transmission: '6-speed manual', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 4, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-accord', manufacturerId: 'honda', make: 'Honda', model: 'Accord 1.5L', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L Turbo I4', horsepower: 192, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-accord-ehev', manufacturerId: 'honda', make: 'Honda', model: 'Accord e:HEV', productionYears: '2024-present', bodyStyle: 'sedan', engine: '2.0L Hybrid', horsepower: 204, transmission: 'E-CVT', drivetrain: 'fwd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-hrv', manufacturerId: 'honda', make: 'Honda', model: 'HR-V', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 119, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-zrv', manufacturerId: 'honda', make: 'Honda', model: 'ZR-V', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 158, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-crv', manufacturerId: 'honda', make: 'Honda', model: 'CR-V', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 190, transmission: 'CVT', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-odyssey', manufacturerId: 'honda', make: 'Honda', model: 'Odyssey', productionYears: '2025-present', bodyStyle: 'mpv', engine: '3.5L V6', horsepower: 280, transmission: '10-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 8, roofType: 'fixed', countryOfOrigin: 'Japan' })
];
