import type { VehicleCatalogModel, VehicleManufacturer } from '../types';

/** UAE-market reference catalog expansion for Splendor operations. */
const now = '2026-08-30T00:00:00.000Z';
const manufacturer = (id: string, name: string, nameAr: string, countryOfOrigin: string): VehicleManufacturer => ({ id, name, nameAr, countryOfOrigin, source: 'oem_official', createdAt: now, updatedAt: now });
const model = (data: Omit<VehicleCatalogModel, 'source' | 'createdAt' | 'updatedAt'>): VehicleCatalogModel => ({ ...data, source: 'oem_official', createdAt: now, updatedAt: now });

export const UAE_CATALOG_EXPANSION_MANUFACTURERS: VehicleManufacturer[] = [
  manufacturer('hyundai', 'Hyundai', 'هيونداي', 'South Korea'),
  manufacturer('kia', 'Kia', 'كيا', 'South Korea'),
  manufacturer('jetour', 'Jetour', 'جيتور', 'China'),
  manufacturer('toyota', 'Toyota', 'تويوتا', 'Japan'),
  manufacturer('nissan', 'Nissan', 'نيسان', 'Japan'),
  manufacturer('honda', 'Honda', 'هوندا', 'Japan'),
  manufacturer('mg', 'MG Motor', 'إم جي', 'United Kingdom / China'),
  manufacturer('geely', 'Geely', 'جيلي', 'China'),
  manufacturer('changan', 'Changan', 'شانجان', 'China'),
  manufacturer('suzuki', 'Suzuki', 'سوزوكي', 'Japan'),
  manufacturer('chery', 'Chery', 'شيري', 'China'),
  manufacturer('haval', 'Haval / GWM', 'هافال / تانك', 'China'),
  manufacturer('mazda', 'Mazda', 'مازدا', 'Japan')
];

export const UAE_CATALOG_EXPANSION_MODELS: VehicleCatalogModel[] = [
  // Hyundai UAE
  model({ id: 'hyundai-elantra', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Elantra', productionYears: '2021-present', bodyStyle: 'sedan', engine: '2.0L I4', horsepower: 147, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-accent', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Accent', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 115, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-creta', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Creta', productionYears: '2022-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 115, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-tucson', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Tucson', productionYears: '2021-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 156, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-sonata', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Sonata', productionYears: '2024-present', bodyStyle: 'sedan', engine: '2.5L I4', horsepower: 191, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-santa-fe', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Santa Fe', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.5L Turbo I4', horsepower: 277, transmission: '8-speed dual-clutch', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-palisade', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Palisade', productionYears: '2020-present', bodyStyle: 'suv', engine: '3.8L V6', horsepower: 291, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-azera', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Azera', productionYears: '2023-present', bodyStyle: 'sedan', engine: '3.5L V6', horsepower: 300, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-grand-i10', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Grand i10', productionYears: '2021-present', bodyStyle: 'hatchback', engine: '1.2L I4', horsepower: 83, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-staria', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Staria', productionYears: '2021-present', bodyStyle: 'mpv', engine: '3.5L V6', horsepower: 272, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 9, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'hyundai-kona', manufacturerId: 'hyundai', make: 'Hyundai', model: 'Kona', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 147, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),

  // Kia UAE
  model({ id: 'kia-pegas', manufacturerId: 'kia', make: 'Kia', model: 'Pegas', productionYears: '2020-present', bodyStyle: 'sedan', engine: '1.4L I4', horsepower: 94, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-picanto', manufacturerId: 'kia', make: 'Kia', model: 'Picanto', productionYears: '2024-present', bodyStyle: 'hatchback', engine: '1.2L I4', horsepower: 83, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k3', manufacturerId: 'kia', make: 'Kia', model: 'K3 / Cerato', productionYears: '2024-present', bodyStyle: 'sedan', engine: '1.6L I4', horsepower: 121, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k5', manufacturerId: 'kia', make: 'Kia', model: 'K5', productionYears: '2021-present', bodyStyle: 'sedan', engine: '2.5L Turbo I4', horsepower: 290, transmission: '8-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-sonet', manufacturerId: 'kia', make: 'Kia', model: 'Sonet', productionYears: '2021-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 115, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-seltos', manufacturerId: 'kia', make: 'Kia', model: 'Seltos', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 158, transmission: '7-speed dual-clutch', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-sportage', manufacturerId: 'kia', make: 'Kia', model: 'Sportage', productionYears: '2025-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 154, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-sorento', manufacturerId: 'kia', make: 'Kia', model: 'Sorento', productionYears: '2024-present', bodyStyle: 'suv', engine: '3.5L V6', horsepower: 268, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-telluride', manufacturerId: 'kia', make: 'Kia', model: 'Telluride', productionYears: '2020-present', bodyStyle: 'suv', engine: '3.8L V6', horsepower: 291, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-carnival', manufacturerId: 'kia', make: 'Kia', model: 'Carnival', productionYears: '2025-present', bodyStyle: 'mpv', engine: '3.5L V6', horsepower: 287, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 8, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),
  model({ id: 'kia-k8', manufacturerId: 'kia', make: 'Kia', model: 'K8', productionYears: '2025-present', bodyStyle: 'sedan', engine: '3.5L V6', horsepower: 296, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'South Korea' }),

  // Jetour UAE
  model({ id: 'jetour-t2', manufacturerId: 'jetour', make: 'Jetour', model: 'T2 Traveller 4WD', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 251, transmission: '7-speed dual-clutch', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-dashing', manufacturerId: 'jetour', make: 'Jetour', model: 'Dashing', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.6L Turbo I4', horsepower: 194, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-x70-plus', manufacturerId: 'jetour', make: 'Jetour', model: 'X70 Plus (7 Seater)', productionYears: '2021-present', bodyStyle: 'suv', engine: '1.6L Turbo I4', horsepower: 194, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-x90-plus', manufacturerId: 'jetour', make: 'Jetour', model: 'X90 Plus', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 254, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-x50', manufacturerId: 'jetour', make: 'Jetour', model: 'X50 Crossover', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 154, transmission: '6-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-t1', manufacturerId: 'jetour', make: 'Jetour', model: 'T1 Compact Off-Roader', productionYears: '2026-present', bodyStyle: 'suv', engine: '1.5L Turbo', horsepower: 156, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'jetour-g700', manufacturerId: 'jetour', make: 'Jetour', model: 'G700 PHEV', productionYears: '2026-present', bodyStyle: 'suv', engine: '2.0L Turbo Hybrid', horsepower: 710, transmission: '3-speed DHT', drivetrain: 'awd', fuelType: 'phev', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Toyota UAE
  model({ id: 'toyota-yaris', manufacturerId: 'toyota', make: 'Toyota', model: 'Yaris Sedan', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 105, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-corolla', manufacturerId: 'toyota', make: 'Toyota', model: 'Corolla 2.0L', productionYears: '2022-present', bodyStyle: 'sedan', engine: '2.0L I4', horsepower: 168, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-camry', manufacturerId: 'toyota', make: 'Toyota', model: 'Camry 2.5L', productionYears: '2025-present', bodyStyle: 'sedan', engine: '2.5L I4', horsepower: 204, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-camry-hybrid', manufacturerId: 'toyota', make: 'Toyota', model: 'Camry Hybrid HEV', productionYears: '2025-present', bodyStyle: 'sedan', engine: '2.5L Hybrid', horsepower: 227, transmission: 'E-CVT', drivetrain: 'fwd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-urban-cruiser', manufacturerId: 'toyota', make: 'Toyota', model: 'Urban Cruiser', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 101, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-rav4', manufacturerId: 'toyota', make: 'Toyota', model: 'RAV4 2.5L', productionYears: '2022-present', bodyStyle: 'suv', engine: '2.5L I4', horsepower: 203, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-fortuner', manufacturerId: 'toyota', make: 'Toyota', model: 'Fortuner 4.0L V6', productionYears: '2022-present', bodyStyle: 'suv', engine: '4.0L V6', horsepower: 235, transmission: '6-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-land-cruiser-prado', manufacturerId: 'toyota', make: 'Toyota', model: 'Land Cruiser Prado (250)', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.4L Turbo I4', horsepower: 278, transmission: '8-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'toyota-land-cruiser-300', manufacturerId: 'toyota', make: 'Toyota', model: 'Land Cruiser 300 V6 TT', productionYears: '2022-present', bodyStyle: 'suv', engine: '3.5L Twin-Turbo V6', horsepower: 409, transmission: '10-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'sunroof', countryOfOrigin: 'Japan' }),

  // Nissan UAE
  model({ id: 'nissan-sunny', manufacturerId: 'nissan', make: 'Nissan', model: 'Sunny 1.6L', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.6L I4', horsepower: 118, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-kicks', manufacturerId: 'nissan', make: 'Nissan', model: 'Kicks', productionYears: '2025-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 139, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-altima', manufacturerId: 'nissan', make: 'Nissan', model: 'Altima 2.5L', productionYears: '2022-present', bodyStyle: 'sedan', engine: '2.5L I4', horsepower: 188, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-xtrail', manufacturerId: 'nissan', make: 'Nissan', model: 'X-Trail (7 Seater)', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.5L I4', horsepower: 181, transmission: 'CVT', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-patrol', manufacturerId: 'nissan', make: 'Nissan', model: 'Patrol Y63 V6 TT', productionYears: '2025-present', bodyStyle: 'suv', engine: '3.5L Twin-Turbo V6', horsepower: 425, transmission: '9-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'nissan-patrol-nismo', manufacturerId: 'nissan', make: 'Nissan', model: 'Patrol Nismo', productionYears: '2025-present', bodyStyle: 'suv', engine: '3.5L Twin-Turbo V6', horsepower: 495, transmission: '9-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'Japan' }),

  // MG UAE
  model({ id: 'mg-5', manufacturerId: 'mg', make: 'MG', model: 'MG 5 Sedan', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 112, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'China' }),
  model({ id: 'mg-gt', manufacturerId: 'mg', make: 'MG', model: 'MG GT 1.5L Turbo', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L Turbo I4', horsepower: 173, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'China' }),
  model({ id: 'mg-zs', manufacturerId: 'mg', make: 'MG', model: 'MG ZS Crossover', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 118, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'mg-rx5', manufacturerId: 'mg', make: 'MG', model: 'MG RX5', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 171, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'mg-one', manufacturerId: 'mg', make: 'MG', model: 'MG One', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 181, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'mg-whale', manufacturerId: 'mg', make: 'MG', model: 'MG Whale Coupe SUV', productionYears: '2024-present', bodyStyle: 'suv_coupe', engine: '2.0L Turbo I4', horsepower: 231, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Geely UAE
  model({ id: 'geely-emgrand', manufacturerId: 'geely', make: 'Geely', model: 'Emgrand 1.5L', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 102, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'China' }),
  model({ id: 'geely-coolray', manufacturerId: 'geely', make: 'Geely', model: 'Coolray 1.5L Turbo', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 172, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'geely-starray', manufacturerId: 'geely', make: 'Geely', model: 'Starray 2.0L Turbo', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 218, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'geely-monjaro', manufacturerId: 'geely', make: 'Geely', model: 'Monjaro 4WD', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 235, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'geely-tugella', manufacturerId: 'geely', make: 'Geely', model: 'Tugella Coupe SUV', productionYears: '2022-present', bodyStyle: 'suv_coupe', engine: '2.0L Turbo I4', horsepower: 238, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Changan UAE
  model({ id: 'changan-alsvin', manufacturerId: 'changan', make: 'Changan', model: 'Alsvin 1.5L', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 105, transmission: '5-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'China' }),
  model({ id: 'changan-eado-plus', manufacturerId: 'changan', make: 'Changan', model: 'Eado Plus 1.4T', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.4L Turbo I4', horsepower: 158, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'changan-cs35-plus', manufacturerId: 'changan', make: 'Changan', model: 'CS35 Plus', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.4L Turbo I4', horsepower: 156, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'changan-cs85-coupe', manufacturerId: 'changan', make: 'Changan', model: 'CS85 Coupe', productionYears: '2023-present', bodyStyle: 'suv_coupe', engine: '2.0L Turbo I4', horsepower: 233, transmission: '8-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'changan-cs95', manufacturerId: 'changan', make: 'Changan', model: 'CS95 4WD 7-Seater', productionYears: '2024-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 233, transmission: '8-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'changan-uni-v', manufacturerId: 'changan', make: 'Changan', model: 'UNI-V Sport Sedan', productionYears: '2024-present', bodyStyle: 'sedan', engine: '1.5L Turbo I4', horsepower: 185, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'changan-uni-k', manufacturerId: 'changan', make: 'Changan', model: 'UNI-K 4WD', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 233, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Suzuki UAE
  model({ id: 'suzuki-swift', manufacturerId: 'suzuki', make: 'Suzuki', model: 'Swift 1.2L', productionYears: '2024-present', bodyStyle: 'hatchback', engine: '1.2L I3 Mild Hybrid', horsepower: 82, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'suzuki-dzire', manufacturerId: 'suzuki', make: 'Suzuki', model: 'Dzire Sedan', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.2L I4', horsepower: 82, transmission: 'AMT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'suzuki-baleno', manufacturerId: 'suzuki', make: 'Suzuki', model: 'Baleno 1.5L', productionYears: '2023-present', bodyStyle: 'hatchback', engine: '1.5L I4', horsepower: 103, transmission: '4-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'suzuki-fronx', manufacturerId: 'suzuki', make: 'Suzuki', model: 'Fronx Crossover', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 103, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'suzuki-jimny', manufacturerId: 'suzuki', make: 'Suzuki', model: 'Jimny 5-Door 4x4', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 101, transmission: '4-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 4, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'suzuki-grand-vitara', manufacturerId: 'suzuki', make: 'Suzuki', model: 'Grand Vitara AllGrip', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L I4 Mild Hybrid', horsepower: 101, transmission: '6-speed automatic', drivetrain: 'awd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),

  // Chery UAE
  model({ id: 'chery-arrizo-8', manufacturerId: 'chery', make: 'Chery', model: 'Arrizo 8', productionYears: '2024-present', bodyStyle: 'sedan', engine: '1.6L Turbo I4', horsepower: 197, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'chery-tiggo-7-pro', manufacturerId: 'chery', make: 'Chery', model: 'Tiggo 7 Pro Max', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.6L Turbo I4', horsepower: 197, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'chery-tiggo-8-pro', manufacturerId: 'chery', make: 'Chery', model: 'Tiggo 8 Pro Max AWD', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 254, transmission: '7-speed dual-clutch', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Haval / GWM UAE
  model({ id: 'haval-jolion', manufacturerId: 'haval', make: 'Haval', model: 'Jolion Pro', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 147, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'haval-h6', manufacturerId: 'haval', make: 'Haval', model: 'H6 2.0L Turbo', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 201, transmission: '7-speed dual-clutch', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'China' }),
  model({ id: 'tank-300', manufacturerId: 'haval', make: 'GWM Tank', model: 'Tank 300 4x4 Off-Roader', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L Turbo I4', horsepower: 224, transmission: '8-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'China' }),
  model({ id: 'tank-500', manufacturerId: 'haval', make: 'GWM Tank', model: 'Tank 500 Luxury V6 4WD', productionYears: '2024-present', bodyStyle: 'suv', engine: '3.0L Twin-Turbo V6', horsepower: 348, transmission: '9-speed automatic', drivetrain: '4wd', fuelType: 'petrol', doors: 4, seats: 7, roofType: 'panoramic', countryOfOrigin: 'China' }),

  // Mazda UAE
  model({ id: 'mazda-3', manufacturerId: 'mazda', make: 'Mazda', model: 'Mazda 3 Sedan', productionYears: '2023-present', bodyStyle: 'sedan', engine: '2.0L I4 Skyactiv-G', horsepower: 153, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'mazda-6', manufacturerId: 'mazda', make: 'Mazda', model: 'Mazda 6 2.5L', productionYears: '2023-present', bodyStyle: 'sedan', engine: '2.5L I4 Skyactiv-G', horsepower: 187, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'mazda-cx30', manufacturerId: 'mazda', make: 'Mazda', model: 'CX-30 Crossover', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.0L I4', horsepower: 153, transmission: '6-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'mazda-cx5', manufacturerId: 'mazda', make: 'Mazda', model: 'CX-5 2.5L AWD', productionYears: '2023-present', bodyStyle: 'suv', engine: '2.5L I4', horsepower: 187, transmission: '6-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'mazda-cx60', manufacturerId: 'mazda', make: 'Mazda', model: 'CX-60 3.3L Turbo I6', productionYears: '2024-present', bodyStyle: 'suv', engine: '3.3L Turbo Inline-6 MHEV', horsepower: 280, transmission: '8-speed automatic', drivetrain: 'awd', fuelType: 'hybrid', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),

  // Honda UAE
  model({ id: 'honda-city', manufacturerId: 'honda', make: 'Honda', model: 'City 1.5L', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.5L I4', horsepower: 119, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-civic', manufacturerId: 'honda', make: 'Honda', model: 'Civic 1.5L Turbo', productionYears: '2022-present', bodyStyle: 'sedan', engine: '1.5L Turbo I4', horsepower: 180, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-accord', manufacturerId: 'honda', make: 'Honda', model: 'Accord 1.5L Turbo', productionYears: '2023-present', bodyStyle: 'sedan', engine: '1.5L Turbo I4', horsepower: 192, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'sunroof', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-hrv', manufacturerId: 'honda', make: 'Honda', model: 'HR-V Crossover', productionYears: '2023-present', bodyStyle: 'suv', engine: '1.5L I4', horsepower: 119, transmission: 'CVT', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'fixed', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-crv', manufacturerId: 'honda', make: 'Honda', model: 'CR-V 1.5L Turbo AWD', productionYears: '2024-present', bodyStyle: 'suv', engine: '1.5L Turbo I4', horsepower: 190, transmission: 'CVT', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 5, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-pilot', manufacturerId: 'honda', make: 'Honda', model: 'Pilot 3.5L V6 AWD', productionYears: '2024-present', bodyStyle: 'suv', engine: '3.5L V6', horsepower: 285, transmission: '10-speed automatic', drivetrain: 'awd', fuelType: 'petrol', doors: 4, seats: 8, roofType: 'panoramic', countryOfOrigin: 'Japan' }),
  model({ id: 'honda-odyssey', manufacturerId: 'honda', make: 'Honda', model: 'Odyssey 3.5L V6 MPV', productionYears: '2025-present', bodyStyle: 'mpv', engine: '3.5L V6', horsepower: 280, transmission: '10-speed automatic', drivetrain: 'fwd', fuelType: 'petrol', doors: 4, seats: 8, roofType: 'fixed', countryOfOrigin: 'Japan' })
];
