import type { Request, Response } from 'express';

/**
 * Vercel compiles this function only after the project build has completed.
 * The build produces one self-contained application handler at the repository
 * root. Keeping this as a static import lets Vercel's function tracer see the
 * generated artifact and its dependency graph instead of relying on a dynamic
 * createRequire path that can be omitted from the deployed lambda package.
 */
// @ts-expect-error -- api-handler.cjs is generated by `bun run build` after typecheck.
import * as bundledModule from '../api-handler.cjs';

const candidate = (bundledModule as any).default || bundledModule;
const handler = candidate as (req: Request, res: Response) => unknown;

export default handler;
