import type { Request, Response } from 'express';

/**
 * Vercel compiles this function only after the project build has completed.
 * The build produces one self-contained Node 22 ESM application handler next
 * to this entrypoint. ESM is intentional: puppeteer-core is ESM-only and a
 * CommonJS bundle crashes during cold start before Express can serve /api.
 */
// @ts-ignore -- api/api-handler.mjs is generated by `bun run build` after typecheck.
import bundledHandler from './api-handler.mjs';

const dispatch = bundledHandler as (req: Request, res: Response) => unknown;

/**
 * Vercel invokes the generated function with a Node-style request before the
 * request has passed through Express. Express normally supplies `req.path`,
 * but api/handler.ts intentionally performs a few security-sensitive route
 * checks before delegating to the Express app. On Vercel those checks used to
 * call `.match()`/`.startsWith()` on an undefined `req.path`, crashing every
 * API request with HTTP 500.
 *
 * Normalize only the pathname here. The original URL/query/body/headers stay
 * untouched and Express still receives the same request object afterwards.
 */
function ensureRequestPath(req: Request): Request {
  const target = req as Request & { path?: string; originalUrl?: string };
  if (typeof target.path === 'string' && target.path.length > 0) return target;

  const rawUrl = typeof target.url === 'string' && target.url.length > 0
    ? target.url
    : (typeof target.originalUrl === 'string' && target.originalUrl.length > 0 ? target.originalUrl : '/');
  let pathname = '/';
  try {
    pathname = new URL(rawUrl, 'http://splendor.internal').pathname || '/';
  } catch {
    pathname = rawUrl.split('?')[0] || '/';
  }

  Object.defineProperty(target, 'path', {
    configurable: true,
    enumerable: false,
    writable: true,
    value: pathname
  });
  return target;
}

const handler = (req: Request, res: Response) => dispatch(ensureRequestPath(req), res);

export default handler;
