import type { Request, Response } from 'express';

/**
 * Vercel compiles this function only after the project build has completed.
 * The build produces one self-contained Node 22 ESM application handler next
 * to this entrypoint. ESM is intentional: puppeteer-core is ESM-only and a
 * CommonJS bundle crashes during cold start before Express can serve /api.
 */
// @ts-ignore -- api/api-handler.mjs is generated by `bun run build` after typecheck.
import bundledHandler from './api-handler.mjs';

const handler = bundledHandler as (req: Request, res: Response) => unknown;

export default handler;
